### ISSUE TITLE
Pair New Device Button is Greyed Out

### ISSUE THREAD

**Issue by Hairimx** [pwr-Solaar/Solaar#1959]
Solaar Version: 1.1.8
Distribution: Ubuntu 22.04.1

Hi!

When I run the Solaar it showing Lightspeed Receiver on the right column, but the pair new device on the right is grey out. 

I'm trying to pair G304 lightspeed dongle with my G903 mouse. I lookup on forum and they said all lightspeed dongle will work with lightspeed mouse.

I tried the solaar pair trough command but it cant find any device. Pairing lock is open for 30 seconds and then ended with device timeout.

Any pointers will be helpful. Thanks!

**Comment by pfps** [comment]
I'm not sure that all lightspeed dongles work with all mice.   If the dongle has 304 printed on it it may not be able to pair it with a 903.


It would help if you provided the output of `solaar show` for your dongle.

Also, run the pair command with debugging on as `solaar -ddd pair`.  You will get a lot of output, as the command tries to find all the devices that might be connected to the receiver.  Post the output.

**Comment by pfps** [comment]
The pair button is greyed out as it is known that Lightspeed receivers cannot pair with multiple devices.  Some receivers that cannot pair with multiple devices can instead replace an existing pairing with a new pairing but it is unknown whether Lightspeed receivers can do even this.

**Comment by Hairimx** [comment]
Thanks for your reply.

Here is the output:

Lightspeed Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:C53F
  Serial       : 
    Firmware   : 44.01.B0005
    Bootloader : 00.02
    Other      : AA.DE
  Has 0 paired device(s) out of a maximum of 1.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)

-ddd pair

`2023-01-06 13:04:55,393,393  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 000080EE PID 00000021: No module named 'hid_parser'
2023-01-06 13:04:55,393,393  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000046D PID 0000C53F: No module named 'hid_parser'
2023-01-06 13:04:55,393,393     INFO [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C53F HID++ None None USB 0 2
2023-01-06 13:04:55,394,394  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000046D PID 0000C53F: No module named 'hid_parser'
2023-01-06 13:04:55,394,394     INFO [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C53F HID++ None None USB 1 2
2023-01-06 13:04:55,394,394  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000046D PID 0000C53F: No module named 'hid_parser'
2023-01-06 13:04:55,394,394     INFO [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C53F HID++ None None USB 2 2
2023-01-06 13:04:55,394,394     INFO [MainThread] logitech_receiver.base: New lock 4
2023-01-06 13:04:55,395,395    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 030000]
2023-01-06 13:04:55,416,416    DEBUG [MainThread] logitech_receiver.base: (4) => r[11 FF 83B5 03C9CF9A7B0101070000000000000000]
2023-01-06 13:04:55,416,416    DEBUG [MainThread] solaar.cli: [/dev/hidraw3] => <LightspeedReceiver(/dev/hidraw3,4)>
2023-01-06 13:04:55,592,592     INFO [MainThread] logitech_receiver.diversion: GDK Keymap set up
2023-01-06 13:04:55,592,592  WARNING [MainThread] logitech_receiver.diversion: rules cannot access active process or modifier keys in Wayland
2023-01-06 13:04:55,592,592  WARNING [MainThread] logitech_receiver.diversion: cannot create uinput device: "/dev/uinput" cannot be opened for writing
2023-01-06 13:04:55,593,593    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 8100 000000]
2023-01-06 13:04:55,603,603    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8002 000000]
2023-01-06 13:04:55,604,604    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8100 000900]
2023-01-06 13:04:56,605,605    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 200000]
2023-01-06 13:04:56,613,613    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:04:56,613,613    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:04:56,613,613    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 040000]
2023-01-06 13:04:56,617,617    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:04:56,617,617    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:04:56,617,617    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 300000]
2023-01-06 13:04:56,621,621    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:04:56,621,621    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:04:56,621,621    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83D5 000000]
2023-01-06 13:04:56,650,650    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 D50200]
2023-01-06 13:04:56,658,658    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83D5}: 2 = invalid address
2023-01-06 13:04:56,658,658    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 241, in register_new_device
    dev = Device(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 129, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error='no wpid or serial')
logitech_receiver.base.NoSuchDevice: {'number': 1, 'receiver': <LightspeedReceiver(/dev/hidraw3,4)>, 'error': 'no wpid or serial'}
2023-01-06 13:04:56,709,709  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,4)>: looked for device 1, not found
2023-01-06 13:04:57,710,710    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 210000]
2023-01-06 13:04:57,731,731    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:04:57,732,732    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:04:57,732,732    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 040000]
2023-01-06 13:04:57,735,735    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:04:57,735,735    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:04:57,735,735    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 310000]
2023-01-06 13:04:57,740,740    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:04:57,740,740    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:04:57,740,740    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83D5 000000]
2023-01-06 13:04:57,771,771    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 D50200]
2023-01-06 13:04:57,777,777    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83D5}: 2 = invalid address
2023-01-06 13:04:57,777,777    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 241, in register_new_device
    dev = Device(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 129, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error='no wpid or serial')
logitech_receiver.base.NoSuchDevice: {'number': 2, 'receiver': <LightspeedReceiver(/dev/hidraw3,4)>, 'error': 'no wpid or serial'}
2023-01-06 13:04:57,783,783  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,4)>: looked for device 2, not found
2023-01-06 13:04:58,788,788    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 220000]
2023-01-06 13:04:58,815,815    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:04:58,815,815    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:04:58,815,815    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 040000]
2023-01-06 13:04:58,829,829    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:04:58,836,836    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:04:58,836,836    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 320000]
2023-01-06 13:05:03,964,964    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:03,965,965    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:03,965,965    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83D5 000000]
2023-01-06 13:05:03,969,969    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 D50200]
2023-01-06 13:05:03,969,969    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83D5}: 2 = invalid address
2023-01-06 13:05:03,970,970    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 241, in register_new_device
    dev = Device(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 129, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error='no wpid or serial')
logitech_receiver.base.NoSuchDevice: {'number': 3, 'receiver': <LightspeedReceiver(/dev/hidraw3,4)>, 'error': 'no wpid or serial'}
2023-01-06 13:05:03,971,971  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,4)>: looked for device 3, not found
2023-01-06 13:05:04,979,979    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 230000]
2023-01-06 13:05:05,003,003    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:05,009,009    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:05,010,010    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 040000]
2023-01-06 13:05:05,070,070    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:05,083,083    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:05,083,083    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 330000]
2023-01-06 13:05:10,384,384    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:10,385,385    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:10,385,385    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83D5 000000]
2023-01-06 13:05:10,389,389    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 D50200]
2023-01-06 13:05:10,390,390    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83D5}: 2 = invalid address
2023-01-06 13:05:10,391,391    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 241, in register_new_device
    dev = Device(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 129, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error='no wpid or serial')
logitech_receiver.base.NoSuchDevice: {'number': 4, 'receiver': <LightspeedReceiver(/dev/hidraw3,4)>, 'error': 'no wpid or serial'}
2023-01-06 13:05:10,392,392  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,4)>: looked for device 4, not found
2023-01-06 13:05:11,400,400    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 240000]
2023-01-06 13:05:11,432,432    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:11,432,432    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:11,432,432    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 040000]
2023-01-06 13:05:11,454,454    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:11,454,454    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:11,454,454    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 340000]
2023-01-06 13:05:16,537,537    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:16,538,538    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:16,538,538    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83D5 000000]
2023-01-06 13:05:16,543,543    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 D50200]
2023-01-06 13:05:16,543,543    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83D5}: 2 = invalid address
2023-01-06 13:05:16,543,543    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 241, in register_new_device
    dev = Device(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 129, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error='no wpid or serial')
logitech_receiver.base.NoSuchDevice: {'number': 5, 'receiver': <LightspeedReceiver(/dev/hidraw3,4)>, 'error': 'no wpid or serial'}
2023-01-06 13:05:16,543,543  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,4)>: looked for device 5, not found
2023-01-06 13:05:17,544,544    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 250000]
2023-01-06 13:05:17,556,556    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:17,556,556    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:17,557,557    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 040000]
2023-01-06 13:05:17,602,602    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:17,611,611    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:17,611,611    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 350000]
2023-01-06 13:05:22,904,904    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:22,904,904    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:22,904,904    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83D5 000000]
2023-01-06 13:05:22,909,909    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 D50200]
2023-01-06 13:05:22,909,909    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83D5}: 2 = invalid address
2023-01-06 13:05:22,909,909    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 241, in register_new_device
    dev = Device(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 129, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error='no wpid or serial')
logitech_receiver.base.NoSuchDevice: {'number': 6, 'receiver': <LightspeedReceiver(/dev/hidraw3,4)>, 'error': 'no wpid or serial'}
2023-01-06 13:05:22,909,909  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,4)>: looked for device 6, not found
2023-01-06 13:05:23,910,910    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 260000]
2023-01-06 13:05:23,999,999    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:23,999,999    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:23,999,999    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 040000]
2023-01-06 13:05:24,044,044    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:24,044,044    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:24,045,045    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 360000]
2023-01-06 13:05:24,131,131    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:24,138,138    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:24,138,138    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83D5 000000]
2023-01-06 13:05:29,676,676    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 D50200]
2023-01-06 13:05:29,679,679    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83D5}: 2 = invalid address
2023-01-06 13:05:29,679,679    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 241, in register_new_device
    dev = Device(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 129, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error='no wpid or serial')
logitech_receiver.base.NoSuchDevice: {'number': 7, 'receiver': <LightspeedReceiver(/dev/hidraw3,4)>, 'error': 'no wpid or serial'}
2023-01-06 13:05:29,679,679  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,4)>: looked for device 7, not found
2023-01-06 13:05:30,681,681    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 270000]
2023-01-06 13:05:30,689,689    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:30,689,689    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:30,689,689    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 040000]
2023-01-06 13:05:30,694,694    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:30,694,694    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:30,694,694    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 370000]
2023-01-06 13:05:30,723,723    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:30,736,736    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:30,737,737    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83D5 000000]
2023-01-06 13:05:35,978,978    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 D50200]
2023-01-06 13:05:35,978,978    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83D5}: 2 = invalid address
2023-01-06 13:05:35,978,978    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 241, in register_new_device
    dev = Device(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 129, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error='no wpid or serial')
logitech_receiver.base.NoSuchDevice: {'number': 8, 'receiver': <LightspeedReceiver(/dev/hidraw3,4)>, 'error': 'no wpid or serial'}
2023-01-06 13:05:35,979,979  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,4)>: looked for device 8, not found
2023-01-06 13:05:36,980,980    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 280000]
2023-01-06 13:05:36,993,993    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:36,993,993    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:36,994,994    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 040000]
2023-01-06 13:05:37,015,015    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:37,021,021    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:37,021,021    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 380000]
2023-01-06 13:05:42,311,311    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:42,312,312    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:42,312,312    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83D5 000000]
2023-01-06 13:05:42,315,315    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 D50200]
2023-01-06 13:05:42,315,315    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83D5}: 2 = invalid address
2023-01-06 13:05:42,315,315    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 241, in register_new_device
    dev = Device(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 129, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error='no wpid or serial')
logitech_receiver.base.NoSuchDevice: {'number': 9, 'receiver': <LightspeedReceiver(/dev/hidraw3,4)>, 'error': 'no wpid or serial'}
2023-01-06 13:05:42,316,316  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,4)>: looked for device 9, not found
2023-01-06 13:05:43,317,317    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 290000]
2023-01-06 13:05:43,329,329    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:43,330,330    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:43,330,330    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 040000]
2023-01-06 13:05:43,355,355    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:43,363,363    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:43,363,363    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 390000]
2023-01-06 13:05:48,519,519    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:48,520,520    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:48,520,520    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83D5 000000]
2023-01-06 13:05:48,523,523    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 D50200]
2023-01-06 13:05:48,524,524    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83D5}: 2 = invalid address
2023-01-06 13:05:48,524,524    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 241, in register_new_device
    dev = Device(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 129, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error='no wpid or serial')
logitech_receiver.base.NoSuchDevice: {'number': 10, 'receiver': <LightspeedReceiver(/dev/hidraw3,4)>, 'error': 'no wpid or serial'}
2023-01-06 13:05:48,524,524  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,4)>: looked for device 10, not found
2023-01-06 13:05:49,525,525    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 2A0000]
2023-01-06 13:05:49,608,608    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:49,623,623    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:49,623,623    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 040000]
2023-01-06 13:05:54,917,917    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:54,917,917    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:54,917,917    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 3A0000]
2023-01-06 13:05:54,922,922    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:54,922,922    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:54,922,922    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83D5 000000]
2023-01-06 13:05:54,928,928    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 D50200]
2023-01-06 13:05:54,928,928    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83D5}: 2 = invalid address
2023-01-06 13:05:54,928,928    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 241, in register_new_device
    dev = Device(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 129, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error='no wpid or serial')
logitech_receiver.base.NoSuchDevice: {'number': 11, 'receiver': <LightspeedReceiver(/dev/hidraw3,4)>, 'error': 'no wpid or serial'}
2023-01-06 13:05:54,928,928  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,4)>: looked for device 11, not found
2023-01-06 13:05:55,929,929    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 2B0000]
2023-01-06 13:05:55,964,964    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:05:55,964,964    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:05:55,964,964    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 040000]
2023-01-06 13:06:01,062,062    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:06:01,062,062    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:06:01,062,062    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 3B0000]
2023-01-06 13:06:01,105,105    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:06:01,105,105    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:06:01,105,105    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83D5 000000]
2023-01-06 13:06:01,140,140    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 D50200]
2023-01-06 13:06:01,168,168    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83D5}: 2 = invalid address
2023-01-06 13:06:01,168,168    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 241, in register_new_device
    dev = Device(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 129, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error='no wpid or serial')
logitech_receiver.base.NoSuchDevice: {'number': 12, 'receiver': <LightspeedReceiver(/dev/hidraw3,4)>, 'error': 'no wpid or serial'}
2023-01-06 13:06:01,185,185  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,4)>: looked for device 12, not found
2023-01-06 13:06:02,193,193    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 2C0000]
2023-01-06 13:06:02,258,258    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:06:02,264,264    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:06:02,264,264    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 040000]
2023-01-06 13:06:02,302,302    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:06:02,310,310    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:06:02,310,310    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 3C0000]
2023-01-06 13:06:02,349,349    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:06:02,355,355    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:06:02,356,356    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83D5 000000]
2023-01-06 13:06:02,412,412    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 D50200]
2023-01-06 13:06:02,417,417    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83D5}: 2 = invalid address
2023-01-06 13:06:02,417,417    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 241, in register_new_device
    dev = Device(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 129, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error='no wpid or serial')
logitech_receiver.base.NoSuchDevice: {'number': 13, 'receiver': <LightspeedReceiver(/dev/hidraw3,4)>, 'error': 'no wpid or serial'}
2023-01-06 13:06:02,417,417  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,4)>: looked for device 13, not found
2023-01-06 13:06:03,418,418    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 2D0000]
2023-01-06 13:06:03,441,441    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:06:03,441,441    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:06:03,441,441    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 040000]
2023-01-06 13:06:08,510,510    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:06:08,510,510    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:06:08,510,510    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 3D0000]
2023-01-06 13:06:08,514,514    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:06:08,514,514    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:06:08,515,515    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83D5 000000]
2023-01-06 13:06:08,518,518    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 D50200]
2023-01-06 13:06:08,518,518    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83D5}: 2 = invalid address
2023-01-06 13:06:08,518,518    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 241, in register_new_device
    dev = Device(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 129, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error='no wpid or serial')
logitech_receiver.base.NoSuchDevice: {'number': 14, 'receiver': <LightspeedReceiver(/dev/hidraw3,4)>, 'error': 'no wpid or serial'}
2023-01-06 13:06:08,519,519  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,4)>: looked for device 14, not found
2023-01-06 13:06:09,520,520    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 2E0000]
2023-01-06 13:06:09,566,566    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:06:09,584,584    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:06:09,584,584    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 040000]
2023-01-06 13:06:14,883,883    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:06:14,883,883    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:06:14,884,884    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 3E0000]
2023-01-06 13:06:14,888,888    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 B50300]
2023-01-06 13:06:14,888,888    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83B5}: 3 = invalid value
2023-01-06 13:06:14,888,888    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83D5 000000]
2023-01-06 13:06:14,894,894    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F83 D50200]
2023-01-06 13:06:14,895,895    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {83D5}: 2 = invalid address
2023-01-06 13:06:14,895,895    ERROR [MainThread] logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 241, in register_new_device
    dev = Device(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 129, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error='no wpid or serial')
logitech_receiver.base.NoSuchDevice: {'number': 15, 'receiver': <LightspeedReceiver(/dev/hidraw3,4)>, 'error': 'no wpid or serial'}
2023-01-06 13:06:14,896,896  WARNING [MainThread] logitech_receiver.receiver: <LightspeedReceiver(/dev/hidraw3,4)>: looked for device 15, not found
2023-01-06 13:06:14,897,897    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 80B2 01001E]
2023-01-06 13:06:14,953,953    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 4A01 000000]
2023-01-06 13:06:14,953,953     INFO [MainThread] logitech_receiver.notifications: <LightspeedReceiver(/dev/hidraw3,4)>: pairing lock is open
2023-01-06 13:06:14,979,979    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 80B2 000000]
Pairing: turn your new device on (timing out in 30 seconds).
2023-01-06 13:06:44,171,171    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 4A00 010000]
2023-01-06 13:06:44,172,172     INFO [MainThread] logitech_receiver.notifications: <LightspeedReceiver(/dev/hidraw3,4)>: pairing lock is closed
2023-01-06 13:06:44,172,172  WARNING [MainThread] logitech_receiver.notifications: pairing error 1: device timeout
solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/cli/__init__.py", line 209, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/share/solaar/lib/solaar/cli/pair.py", line 135, in run
    raise Exception('pairing failed: %s' % error)
Exception: pairing failed: device timeout
`

On the mulltiple devices, the solaar acctually mentioned no device paired.

Thanks!

**Comment by pfps** [comment]
Solaar is being very cautious in determining what is connected to the receiver as there is at least one  case where a device is connected in a way different from what is possible according to documentation about receivers.   So Solaar is trying all possible device numbers, from 0 to 15, and not finding anything.  I think that it is possible to optimize this but after trying all the numbers Solaar sets up to do the pairing.

But after the pairing lock opens the receiver does not report any successful pairing.   Pairing is done completely by the receiver so there is no indication as to what is going on until the receiver reports that no device connected before the connection time ended.  If your did turn on your device during the pairing period and your device did send a connection request to the receiver then this receiver probably cannot connect to your device.

If you have a G304 device I would try with that device, just to see if Solaar can actually do the pairing.

By the way, how did you unpair the G304 device from the receiver?

**Comment by pfps** [comment]
Can you provide a screenshot of the Solaar main window showing the receiver.  Please do this with the information pane open.  (Click on the light bulb or information button to show this pane.)

**Comment by pfps** [comment]
PR #1961 should fix the greyed out pair button.  But  it doesn't to anything except allow pairing attempts in your situation.  But if your device can't pair with your receiver then it can't.  But please try this PR and report back if the pair button is now active.

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1961, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1961/head:pull_1961
git checkout pull_1961
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1961
git fetch origin pull/1961/head
git reset --hard FETCH_HEAD
```

**Comment by Hairimx** [comment]
Update:

1. Now the pair new device is available, you fixed it.
2. But it still not pairing, but most probably because its incompatible, which is interesting because lot of people are mixing their speedlight dongle and it works for them, but it G304 might be exception.

Sorry if this is a stupid question, but is there a  way to trick the receiver to open up whole range of mouse so it can pair?

Thanks for providing the git syntax, i'm not really familiar with git only basic command terminal and little of basic programming. Do you still need the screenshot now that its working (the button now is clickable)?

**Comment by pfps** [comment]
No need for the screenshot any more.

The receiver should have somewhere what kinds of devices it can pair with, but I don't know how to find the information.

If you have access to a Windows machine try using the Logitech software to pair there.

**Comment by pfps** [comment]
It turns out that there is no available way to determine which devices a Lightspeed receiver can pair with.  The information is in the receiver but not accessible via any documented interface.  So one has to resort to looking at the label on the receiver, which should say what kind of device it can be paired with.
