### ISSUE TITLE
Exception in thread ReceiverListener:hidraw3 after launching Solaar : TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by Vinzainer** [pwr-Solaar/Solaar#2967]
- Solaar version: 1.1.11+dfsg-2
- Distribution: Ubuntu 24.04.3 LTS
- Kernel version: Linux 6.14.0-33-generic x86_64 GNU/Linux
- Output of `solaar show`:

<details>

```
solaar version 1.1.11+dfsg-2


MX Mechanical Mini
     Device path  : /dev/hidraw3
     USB id       : 046d:B367
     Codename     : MX MCHNCL M
     Kind         : ?
     Protocol     : HID++ 4.5
     Serial number: 
     Model ID:      B36700000000
     Unit ID:       B3EC136E
        Bootloader: BL1 50.02.B0012
          Firmware: RBK 72.02.B0012
             Other: 
     Supports 33 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V4     
            Firmware: Bootloader BL1 50.02.B0012 B367B7232F6A
            Firmware: Firmware RBK 72.02.B0012 B367B7232F6A
            Firmware: Other   
            Unit ID: B3EC136E  Model ID: B36700000000  Transport IDs: {'btleid': 'B367'}
         3: DEVICE NAME            {0005} V0     
            Name: MX Mechanical Mini
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
         6: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: MX MCHNCL M
         7: UNIFIED BATTERY        {1004} V3     
            Battery: 40%, recharging.
         8: REPROG CONTROLS V4     {1B04} V5     
            Interception des boutons/touches (saved): {MultiPlatform Search:Normal, Backlight Down:Interception, Backlight Up:Normal, Mute Fn:Normal, Volume Down Fn:Normal, Volume Up Fn:Normal, Voice Dictation:Normal, Open Emoji Panel:Normal, Snipping Tool:Normal, Grave Accent:Normal, Tab Key:Normal, Caps Lock:Normal, Left Shift:Normal, Left Control:Normal, Left Option/Start:Normal, Left Command/Alt:Normal, Right Command/Alt:Normal, Right Shift:Normal, Delete:Normal, Home:Normal, End:Normal, Page Up:Normal, Page Down:Normal, Mute Microphone:Interception, Backslash:Normal, Right Option/Start/2:Normal, Play Pause:Normal}
            Interception des boutons/touches        : {MultiPlatform Search:Normal, Backlight Down:Interception, Backlight Up:Normal, Mute Fn:Interception, Volume Down Fn:Normal, Volume Up Fn:Normal, Voice Dictation:Normal, Open Emoji Panel:Normal, Snipping Tool:Normal, Grave Accent:Normal, Tab Key:Normal, Caps Lock:Normal, Left Shift:Normal, Left Control:Normal, Left Option/Start:Normal, Left Command/Alt:Normal, Right Command/Alt:Normal, Right Shift:Normal, Delete:Normal, Home:Normal, End:Normal, Page Up:Normal, Page Down:Normal, Mute Microphone:Interception, Backslash:Normal, Right Option/Start/2:Normal, Play Pause:Normal}
         9: CHANGE HOST            {1814} V1     
            Changer d'hôte        : 1:vincent-p14s
        10: HOSTS INFO             {1815} V2     
            Host 0 (paired): vincent-p14s
            Host 1 (paired): MacBook Pro de Gabin
            Host 2 (unpaired): 
        11: BACKLIGHT2             {1982} V2     
            Rétroéclairage (saved): Disabled
solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/cli/__init__.py", line 217, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/share/solaar/lib/solaar/cli/show.py", line 312, in run
    _print_device(d)
  File "/usr/share/solaar/lib/solaar/cli/show.py", line 243, in _print_device
    v = setting.val_to_string(setting.read(False))
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/share/solaar/lib/logitech_receiver/settings.py", line 287, in read
    self._value = self._validator.validate_read(reply)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/solaar/lib/logitech_receiver/settings.py", line 1026, in validate_read
    reply_value = _bytes2int(reply_bytes[self._read_skip_byte_count:self._read_skip_byte_count + self._byte_count])
                             ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not subscriptable
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
- 1.1.11+dfsg-2
- _NAME: MX Mechanical Mini
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi, speed-change, backlight_level, backlight_duration_hands_out,
    backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, reprogrammable-keys, persistent-remappable-keys, crown-smooth,
    divert-crown, divert-gkeys, m-key-leds, mr-key-led, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4100
  _modelId: B36700000000
  _sensitive: {backlight: true, divert-keys: true, multiplatform: true}
  _unitId: B3EC136E
  backlight: 0xff
  change-host: null
  disable-keyboard-keys: {0x1: false, 0x4: false, 0x8: false, 0x10: false}
  divert-keys: {0xd4: 0x0, 0xe2: 0x1, 0xe3: 0x0, 0xe7: 0x0, 0xe8: 0x0, 0xe9: 0x0, 0x103: 0x0, 0x108: 0x0, 0x10a: 0x0, 0x10b: 0x0, 0x10c: 0x0, 0x10d: 0x0,
    0x10e: 0x0, 0x10f: 0x0, 0x110: 0x0, 0x111: 0x0, 0x112: 0x0, 0x115: 0x0, 0x117: 0x0, 0x118: 0x0, 0x119: 0x0, 0x11a: 0x0, 0x11b: 0x0, 0x11c: 0x1, 0x11e: 0x0,
    0x13c: 0x0, 0x141: 0x0}
  fn-swap: true
  multiplatform: 0x0
```
</details>

- Errors or warrnings from Solaar:
<details>

```
2025-10-07 17:51:51,172,172     INFO [MainThread] solaar.gtk: version 1.1.11+dfsg-2, language fr_FR (UTF-8)
2025-10-07 17:51:51,391,391     INFO [MainThread] logitech_receiver.diversion: GDK Keymap set up
2025-10-07 17:51:51,394,394     INFO [MainThread] logitech_receiver.diversion: loaded 1 rules from /root/.config/solaar/rules.yaml
2025-10-07 17:51:51,418,418     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
2025-10-07 17:51:51,853,853     INFO [MainThread] solaar.ui.notify: starting desktop notifications
2025-10-07 17:51:51,879,879  WARNING [MainThread] solaar.ui.icons: failed to detect icons
2025-10-07 17:51:51,978,978     INFO [MainThread] solaar.listener: starting receiver listening threads
2025-10-07 17:51:51,986,986  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for DEVICE /dev/hidraw0 BID 0003 VID 0000413C PID 00002514: No module named 'hid_parser'
2025-10-07 17:51:51,988,988  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for DEVICE /dev/hidraw1 BID 0003 VID 0000413C PID 00002514: No module named 'hid_parser'
2025-10-07 17:51:51,990,990  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for DEVICE /dev/hidraw2 BID 0003 VID 0000413C PID 00002514: No module named 'hid_parser'
2025-10-07 17:51:51,991,991  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for DEVICE /dev/hidraw3 BID 0005 VID 0000046D PID 0000B367: No module named 'hid_parser'
2025-10-07 17:51:51,991,991     INFO [MainThread] hidapi.udev: Found device /dev/hidraw3 BID 0005 VID 0000046D PID 0000B367 HID++ None None USB None None
2025-10-07 17:51:51,991,991     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw3', bus_id=5, vendor_id='046D', product_id='B367', interface=None, driver='hid-generic', manufacturer=None, product=None, serial='d4:42:64:31:06:ae', release=None, isDevice=True, hidpp_short=None, hidpp_long=None)
2025-10-07 17:51:51,991,991     INFO [MainThread] hidapi.udev: OPEN PATH /dev/hidraw3
2025-10-07 17:51:51,992,992     INFO [ReceiverListener:hidraw3] logitech_receiver.base: New lock <_ThreadedHandle(/dev/hidraw3)>
2025-10-07 17:51:51,992,992     INFO [ReceiverListener:hidraw3] logitech_receiver.listener: started with <Device(255,B367,MX Mechanical Mini,)> (13)
2025-10-07 17:51:52,427,427     INFO [ReceiverListener:hidraw3] solaar.listener: <Device(255,B367,MX Mechanical Mini,)>: notifications listener has started (13)
2025-10-07 17:51:52,516,516     INFO [ReceiverListener:hidraw3] solaar.listener: status_changed <Device(255,B367,MX Mechanical Mini,)>: paired online, {'NOTIFICATION FLAGS': False} (0) 
2025-10-07 17:51:52,607,607     INFO [MainThread] hidapi.udev: OPEN PATH /dev/hidraw3
2025-10-07 17:51:52,653,653  WARNING [MainThread] solaar.ui.icons: icon battery-missing not found in current theme
2025-10-07 17:51:53,194,194  WARNING [MainThread] solaar.ui.icons: icon battery-good-charging not found in current theme
2025-10-07 17:51:53,237,237     INFO [ReceiverListener:hidraw3] solaar.listener: status_changed <Device(255,B367,MX Mechanical Mini,)>: paired online, {'NOTIFICATION FLAGS': False, 'BATTERY LEVEL': 40, 'BATTERY STATUS': NamedInt(1, 'recharging'), 'BATTERY NEXT LEVEL': None, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': True, 'ERROR': None} (0) 
2025-10-07 17:51:53,373,373  WARNING [MainThread] solaar.ui.icons: icon battery-good-charging not found in current theme
2025-10-07 17:51:55,983,983     INFO [ReceiverListener:hidraw3] logitech_receiver.status: <Device(255,B367,MX Mechanical Mini,)> pushing device settings [<Setting([fonctionnalité:choice] MX MCHNCL M:backlight=None)>, <Setting([fonctionnalité:toggle] MX MCHNCL M:fn-swap=None)>, <Setting([fonctionnalité:map choice] MX MCHNCL M:divert-keys=None)>, <Setting([fonctionnalité:multiple toggle] MX MCHNCL M:disable-keyboard-keys=None)>, <Setting([fonctionnalité:choice] MX MCHNCL M:multiplatform=None)>, <Setting([fonctionnalité:choice] MX MCHNCL M:change-host=None)>]
2025-10-07 17:51:55,988,988    ERROR [AsyncUI] solaar.tasks: calling <function _read_async.<locals>._do_read at 0x7849aebe5bc0>
Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/tasks.py", line 65, in run
    function(*args, **kwargs)
  File "/usr/share/solaar/lib/solaar/ui/config_panel.py", line 41, in _do_read
    v = s.read(not force)
        ^^^^^^^^^^^^^^^^^
  File "/usr/share/solaar/lib/logitech_receiver/settings.py", line 287, in read
    self._value = self._validator.validate_read(reply)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/solaar/lib/logitech_receiver/settings.py", line 1026, in validate_read
    reply_value = _bytes2int(reply_bytes[self._read_skip_byte_count:self._read_skip_byte_count + self._byte_count])
                             ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not subscriptable
Exception in thread ReceiverListener:hidraw3:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
2025-10-07 17:51:56,027,027     INFO [AsyncUI] hidapi.udev: OPEN PATH /dev/hidraw3
    self.run()
  File "/usr/share/solaar/lib/logitech_receiver/listener.py", line 160, in run
    self.receiver.status.changed(True, reason='initialization')
  File "/usr/share/solaar/lib/logitech_receiver/status.py", line 291, in changed
    _settings.apply_all_settings(d)
  File "/usr/share/solaar/lib/logitech_receiver/settings.py", line 1560, in apply_all_settings
    s.apply()
  File "/usr/share/solaar/lib/logitech_receiver/settings.py", line 349, in apply
    value = self.read(self.persist)  # Don't use persisted value if setting doesn't persist
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/solaar/lib/logitech_receiver/settings.py", line 287, in read
    self._value = self._validator.validate_read(reply)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/solaar/lib/logitech_receiver/settings.py", line 1026, in validate_read
    reply_value = _bytes2int(reply_bytes[self._read_skip_byte_count:self._read_skip_byte_count + self._byte_count])
                             ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not subscriptable
2025-10-07 17:51:56,118,118  WARNING [MainThread] solaar.ui.icons: icon battery-good-charging not found in current theme
2025-10-07 17:51:56,208,208  WARNING [MainThread] solaar.ui.icons: icon battery-good-charging not found in current theme
2025-10-07 17:51:56,298,298  WARNING [MainThread] solaar.ui.icons: icon battery-good-charging not found in current theme
```
</details>

**Describe the bug**
After execution of "sudo solaar" I get an exception for a TypeError. Consequently Solaar is unable to catch the key pressing and none of the rules are functioning.

**To Reproduce**
1. Run "sudo solaar"

**Comment by pfps** [comment]
I suggest first updating to 1.1.14 or even the version here.  Several bugs that caused problems like this have been fixed.

**Comment by Vinzainer** [comment]
Well, I didn't realize I wasn't up to date. The error is gone but still not interception, I can control the backlight but the rules aren't applied to the key presses.

**Comment by pfps** [comment]
Solaar should not be run as root as it will then not pick up any of your configuration information.

**Comment by Vinzainer** [comment]
Thank you for your help, I can only get one key to be mapped (the MicMute), but every other one, including the predefined backlight up and down does not work. I also can't use the swap Fx function. Shoud I create a new issue ?

**Comment by pfps** [comment]
Yes, please.  Include you rule file along with the other requested information.
