### ISSUE TITLE
solaar gui pops up every time the mouse wakes

### ISSUE THREAD

**Issue by mflannery** [pwr-Solaar/Solaar#398]
I have a logitech M525 mouse and a K750 keyboard attached to my unified receiver.  I recently, when the mouse wakes up, the solaar gui pops up on the desktop.  I would prefer that the gui only pop up with warnings or errors like low battery.  Is there a setting that will prevent the gui from popping up on the desktop when the mouse wakes up?

**Comment by Vaesper** [comment]
:+1: One of the most aggravating anti-features of Solaar. Imho just disable it altogether. There is no reason anyone should be interested in being notified every time they bump into their mouse.

**Comment by zoqaeski** [comment]
I tried disabling notifications for Solaar from the GNOME settings panel, and that didn't seem to have any effect at all.

**Comment by georgmu** [comment]
I have the same issue. "Invalid" battery every now and then, even if battery is at 70%.
Maybe there should be a rate-limiting to only show the warning once a day or once a week...

**Comment by aquatix** [comment]
Same here, with 90% battery left. Is 'invalid' an error in reading the battery level, or something else? Maybe try a few more times to read in that case before popping up, it's getting a bit chatty :)

**Comment by ivandokov** [comment]
I really hate this wakeup notification! Using it with elementaryOS it is disturbing me by making me check the notification center again and again without any reason to do it. For me this is useless notification and can get removed or at least give us option to disable it.

**Comment by ckol** [comment]
Same where with an M705 Mouse. Everytime the mouse wakes up, a low battery warning is displayed, which is very annoying. I don't care about a low battery condition as long as it's still working perfectly! I'll prefer to swap batteries when they are really dead. Preferrable solutions: Disable/Enable/Rate Limit user notifications.

Here, using 0.9.2 the first time over a weak battery condition, the notifications only pop up when the battery really went below 10% or 5% (documentation?). With a full battery, I didn't get notifications.

**Comment by jrswgtr** [comment]
Having the same issue on Ubuntu 18.04

**Comment by Tiedemate** [comment]
Same here with a K750 and a M175. It's driving me nuts ;-)

**Comment by VerumDigital** [comment]
I had the same issue. Everytime I wake my mouse after sleep, solaar window would pop up and it would should a notification. It was pretty annoying.
One way to fix the popup window or notification is to close the solaar and remove auto start entry so it doesn't start at boot. Once you have paired your devices you don't need it anyway.

**Comment by lovedigit** [comment]
I had the same issue. Everytime I wake my mouse after sleep, solaar window would pop up and it would should a notification. It was pretty annoying.
One way to fix the popup window or notification is to close the solaar and remove auto start entry so it doesn't start at boot. Once you have paired your devices you don't need it anyway.

**Comment by jasontibbitts** [comment]
I'm not seeing this behavior using current git HEAD and an MX Master.  I also don't see it in the current Fedora version (which is from a couple of weeks ago, before the recent flurry of merged PRs).  I suppose it's possible I'm not letting the mouse sit for long enough but I can also cycle the power switch on the bottom of mouse and even unplug and reconnect the receiver without seeing any popups.

**Comment by ckol** [comment]
Hello!

This behaviour seems (on my side) to appear only when the battery status of the mouse is low (i.e. at 10%).
It seems that Solaar trys to note the user about the low battery status every time the mouse wakes up.
This is way more annoying than simply running out of battery.

What is the function and/or purpose of Solaar being active, when there is no need to pair new devices?

Regards,

Clemens

**Comment by Lekensteyn** [comment]
I agree that the notification is annoying and it should be possible to disable it (or be smarter like not warning every time the device is reconnected in a short time?). With modern desktop integration (as is done with KDE Plasma), it uses UPower to learn about the battery status.

> What is the function and/or purpose of Solaar being active, when there is no need to pair new devices?

Restoring settings like fn-swap. If you just need battery status (like I do), then you do not need it on modern desktops (see above). For pairing, I still tend to use ltunify since it is a simple CLI program.

**Comment by Tiedemate** [comment]
Is it that difficult to fix? (This is a serious question, I have no clue about programming...)

**Comment by Vaesper** [comment]
It seems to already have been fixed in master; I'm not getting these issues anymore on the latest version of the package on arch (no idea which commit that was built with, but it was last updated some 2 weeks ago). Maybe this issue should be closed?

**Comment by Tiedemate** [comment]
Sounds good! I would like to test it also (on Ubuntu). I have cloned into the the Solaar git repo, but now I don't know how to compile it. Can anyone give me some hints?

**Comment by walterramjet** [comment]
most annoying thing is in the middle of netflix movie or youtube video and accidently bump the mouse and BAM! the moust display pops up.  There was a short time after an update that it stopped and then got another update a couple months later and back to popping up when you least expect it.  It has NOTHING to do with low battery.  its just a pain in the arse!

**Comment by hopeseekr** [comment]
`sudo systemctl stop upower`.

**Comment by hopeseekr** [comment]
`sudo systemctl stop upower`

**Comment by walterramjet** [comment]
Theodore,

why are you sending this message?  I dont know what it means.  have you any info on why the solaar gui keeps popping up whenever I touch my mouse?

thanks,
Walt

________________________________

**Comment by Igetin** [comment]
I have this problem with the K540 keyboard. I’ve had the M705 mouse for a while, but it has been working fine without triggering the GUI. I recenly got the K540 and paired it with the same receiver that the M705 is paired with. Solaar’s GUI pops up every time the keyboard wakes.

**Comment by walterramjet** [comment]
this was so annoying, I switched to Linux Mint.  problem solved

**Comment by pfps** [comment]
Is this a problem with the version of Solaar from this repository?

**Comment by eliezerlp** [comment]
> this was so annoying, I switched to Linux Mint. problem solved

Same things happens to me on Linux Mint 19.2 using Solaar 0.9.2+dfsg-8 installed from the default Ubuntu bionic repos.

**Comment by pfps** [comment]
Version 0.9.2 is old.  The version from this repository doesn't have the problem for me in either Xubuntu 18.04 or Fedora 31 with XFCE.   Please try downloading this version to see if the problem is still active.

**Comment by nightsky30** [comment]
With the dev version of Ubuntu/Xubuntu 20.04 it looks like they've updated to Solaar 1.0.1+dfsg-3 :tada:

**Comment by pfps** [comment]
This should be fixed in the current version, so I'm closing the issue.  If it is a problem in the current version (1.0.2-rc1 or later) please comment and the issue will be reopened.

**Comment by richaardvark** [comment]
I'm running Debian 10 (buster), using the latest version from the repository (0.9.2) and this is still happening with my M215 2nd Generation wireless mouse. Battery is at 90%, but it randomly pops up "Invalid Battery" several times an hour and every time I restart my computer. How can I update to the latest version? Do I need to build it manually?

**Comment by pfps** [comment]
Version 0.9.2 is very old.  You might be able to use the Ubuntu git PPA version of Solaar as described on https://github.com/pwr-Solaar/Solaar to get the current version (1.0.2-rc1 but still identified as 1.0.1).   Alternatively follow the install directions in https://github.com/pwr-Solaar/Solaar

Solaar uses notifications - if you don't want to see them you should be able to user your desktop management system to suppress notifications from Solaar.

**Comment by richaardvark** [comment]
I'm just going to uninstall. :(  I have all the prerequisites to build manually. When I get to the second step ("sudo bin/solaar"), the annoying window pops up like it always does, and the following error is given:
`(solaar:31175): Gdk-CRITICAL **: 18:55:06.020: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

Perhaps this is the error that has been causing this issue the whole time?

**Comment by richaardvark** [comment]
> I'm just going to uninstall. :( I have all the prerequisites to build manually. When I get to the second step ("sudo bin/solaar"), the annoying window pops up like it always does, and the following error is given:
> `(solaar:31175): Gdk-CRITICAL **: 18:55:06.020: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed`
> 
> Perhaps this is the error that has been causing this issue the whole time?

Never mind. Google says to ignore that Gdk error. I continued on and am now running Solaar 1.0.1. I will report back if the "invalid battery"/frequent window pop up bug happens again. So far no battery warnings, so that is a good sign!

**Comment by pfps** [comment]
If you have Solaar running from a repository you shouldn't need to the sudo, as that is only needed to get around permissions problems and the full install should set up permissions correctly using a udev rule.

When you start Solaar you probably are seeing two things should up on your screen - the main Solaar window and a desktop notification.  If you don't want the main Solaar window to show up  your can use the `--window=hide` flag.  If you don't want notifications to show up you should be able to set that up in your desktop environment.  (In XFCE it is part of the Notifications item in the Settings menu.)

**Comment by Starvexx** [comment]
> If you have Solaar running from a repository you shouldn't need to the sudo, as that is only needed to get around permissions problems and the full install should set up permissions correctly using a udev rule.
> 
> When you start Solaar you probably are seeing two things should up on your screen - the main Solaar window and a desktop notification. If you don't want the main Solaar window to show up your can use the `--window=hide` flag. If you don't want notifications to show up you should be able to set that up in your desktop environment. (In XFCE it is part of the Notifications item in the Settings menu.)

Thanks, that was very helpful.

**Comment by Lew-Rockwell-Fan** [comment]
Didn't happen for the first couple of days after installing 0.9.2+dfsg-8 in Ubuntu 18.04 with an M-575 trackball and an MX Keys keyboard. Then it started popping up and stealing focus constantly. Even setting the Openbox wm to keep it on the bottom layer didn't fix the stealing focus.  But if I don't need this once paired, I don't want it running anyway. So if somebody can tell me where it's autostarting from, I'll stop that. I didn't add it to my Openbox autostart script and it's not in any other place I know to look. Otherwise I'll just uninstall it. No biggie. I can always install it again when needed. I eagerly await support for the "zone" series headphones. I'm not buying any until there's gnu/linux support. (Hint to any Logi employee listening - maybe y'all should throw some $ toward these folks).

**Comment by pfps** [comment]
@Tiedemate Hi:  If you are still using Solaar and still have your M175 mouse can you provide the output of `solaar show` when the mouse is connected and active?  Thanks.

**Comment by Tiedemate** [comment]
I still have the M175, but I don't have the issue anymore. I am running solaar 1.1.14-2, on KDE 6.3.4 (Kubuntu 25.04) and everything is fine now. Maybe it's because I use an LFP rechargeable battery whose electronics always maintain 1,5V no matter the state of charge. However here is the output:

solaar show
rules cannot access modifier keys in Wayland, accessing process only works on GNOME with Solaar Gnome extension installed
solaar version 1.1.14-2

Unifying Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:C52B
  Serial       : EC219AC2
  C Pending    : ff
    0          : 12.11.B0032
    1          : 04.16
    3          : AA.AA
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 1=195, 2=74

  1: Wireless Mouse M175
     Device path  : /dev/hidraw2
     WPID         : 4008
     Codename     : M175
     Kind         : mouse
     Protocol     : HID++ 2.0
     Report Rate : 8ms
     Serial number: 16E46E8C
     Model ID:      000000000000
     Unit ID:       00000000
                 0: RQM 40.00.B0016
     The power switch is located on the base.
     Supports 21 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V0     
            Firmware: 0 RQM 40.00.B0016 4008
            Unit ID: 00000000  Model ID: 000000000000  Transport IDs: {}
         3: DEVICE NAME            {0005} V0     
            Name: Wireless Mouse M185
            Kind: mouse
         4: BATTERY STATUS         {1000} V0     
            Battery: 70%, 0, next level 5%.
         5: unknown:1830           {1830} V0    internal, hidden 
         6: unknown:1850           {1850} V0    internal, hidden 
         7: unknown:1860           {1860} V0    internal, hidden 
         8: unknown:1890           {1890} V0    internal, hidden 
         9: unknown:18A0           {18A0} V0    internal, hidden 
        10: unknown:18C0           {18C0} V0    internal, hidden 
        11: WIRELESS DEVICE STATUS {1D4B} V0     
        12: unknown:1DF3           {1DF3} V0    internal, hidden 
        13: REPROG CONTROLS        {1B00} V0     
        14: REMAINING PAIRING      {1DF0} V0    hidden 
            Remaining Pairings: 117
        15: unknown:1E00           {1E00} V0    hidden 
        16: unknown:1E80           {1E80} V0    internal, hidden 
        17: unknown:1E90           {1E90} V0    internal, hidden 
        18: unknown:1F03           {1F03} V0    internal, hidden 
        19: VERTICAL SCROLLING     {2100} V0     
            Roller type: standard
            Ratchet per turn: 24
            Scroll lines: 0
        20: MOUSE POINTER          {2200} V0     
            DPI: 1000
            Acceleration: low
            Override OS ballistics
            No vertical tuning, standard mice
     Battery: 70%, 0, next level 5%.

**Comment by pfps** [comment]
Thanks

**Comment by pfps** [comment]
I see that the mouse identifies itself as an M185.  Do you think that is correct?

**Comment by Tiedemate** [comment]
No idea. I think it was was written on the mouse below the logitech logo, but that's gone now (it's a well used mouse..). Here's a pic: https://bilderupload.org/bild/146395383-pxl-20250912-164048922

With the part number I get one hit on french ebay leading to a M175.

On quora I found:
"Just the intended usage
- M175 is in Business Line
- M185 is for Personal Line

Other than that both devices share the same specs."

**Comment by pfps** [comment]
Thanks.  That makes marketing "sense".

**Comment by Lew-Rockwell-Fan** [comment]
More a feature request than addressing the bug itself, but related. Most wouldn't be bothered by this if Solaar didn't set itself up to autostart and daemonize by default with no obvious way to configure it otherwise. This really shouldn't happen without giving the user a choice. I've moved on to another distro since my earlier comment, and I just put "killall solaar" in my post login script. I'm sure if I spent enough time at it I could eventually track down a way to keep it from autostarting altogether, or, failing that, kill it earlier, but that suffices for now.

**Comment by pfps** [comment]
The autostart is part of a distribution, which is not part of Solaar itself.  If you run Solaar from the command line it works mostly like a regular program.  There is a difference between Quitting and closing, but that is because Solaar needs to continue to monitor devices else changes are forgotten.
