### ISSUE TITLE
Solaar loses configs on MX Master 2S after suspend

### ISSUE THREAD

**Issue by witheld9** [pwr-Solaar/Solaar#467]
Version: master
OS: Kubuntu 17.10

Whenever the computer returns from sleep, Solaar does not send over the config again, leaving the mouse in the default state.

**Comment by witheld9** [comment]
https://github.com/pwr/Solaar/pull/458

This pull fixes it the issue so please merge

**Comment by witheld9** [comment]
Nevermind, only occasionally fixes it.

**Comment by witheld9** [comment]
Okay so after a suspend or any loss of connection other than a physical power cycle, the mouse sends

`10 FF 8000 000000`

Which presumably is just the mouse letting you know that it's lost it's volatile memory. I'm trying to patch Solaar but the weirdnest of that is making the notification get sent somewhere I don't expect or not creating a notification at all

**Comment by witheld9** [comment]
Okay this is even easier, `10 FF 8000 000000` is sent by the receiver. We should probably just reset everything if we get that.

Anyone alive out there to suggest how?

**Comment by kdickerson** [comment]
Possibly same issue as #356?

**Comment by witheld9** [comment]
Not exactly. That bug is crazy, it does detect the device reconnect but at some point in the process it saves the default dpi to your settings.

In this one, it doesn't notice that it needs to reconfigure the devices at all. I've fixed this bug(but need to get it into a releasable state), and then I still get to deal with that one

**Comment by witheld9** [comment]
Fixes are coming

**Comment by NeonHorizon** [comment]
Any news on this, or any way I can help?
I just bought a Master 3 and every time I come out of suspend I have to close and reopen Solaar to change the DPI from the 1000dpi default and also enable high wheel resolution.

**Comment by pfps** [comment]
I expect that this is an occurrence of Solaar not saving settings for features discovered at run time so PR #649 should solve the problem.

**Comment by pfps** [comment]
With PR #649 merged, the version of Solaar in this repository should fix your problem.  Please clone Solaar from this repository and run it from the download directory as bin/solaar.   If the problem is still active please add a comment to this issue.

**Comment by NeonHorizon** [comment]
I'm running the version from ppa:solaar-unifying/ppa
1.0.1+dfsg-1+git864-91bcfa2-202001220517~ubuntu18.04.1
which is after the commit and its still showing the problem.

Personally I've solved the issue with a script which runs whenever my computer wakes from sleep:
sleep 3
killall solaar
/usr/bin/solaar &

But obviously this is a bit of a hack....

**Comment by pfps** [comment]
Closing due to no response from original poster.

**Comment by aleho** [comment]
Can confirm: Current master works, DPI setting persists after wakeup.
