### ISSUE TITLE
Logitech MX Master 3 not regaining config when waking from sleep

### ISSUE THREAD

**Issue by NeonHorizon** [pwr-Solaar/Solaar#686]
**Information**
- Solaar version: 1.0.1 commit 079f2dacd4a5554c652191a24f0b4f474038dc7d
- Distribution: KDE Neon (Ubuntu 18.04)
- Kernel version (ex. `uname -srmo`): Linux 4.15.0-88-generic x86_64 GNU/Linux
- Output of `solaar show`:
```
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : 8C069CEA
    Firmware   : 12.11.B0032
    Bootloader : 04.16
    Other      : AA.AA
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=186

  1: Wireless Mouse MX Master 3
     Codename     : MX Master 3
     Kind         : mouse
     Wireless PID : 4082
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: BA137AAB
        Bootloader: BOT 95.00.B0013
          Firmware: MPM 19.00.B0013
             Other: 
     The power switch is located on the base.
     Supports 34 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: CRYPTO ID              {0021}   
         7: BATTERY STATUS         {1000}   
         8: REPROG CONTROLS V4     {1B04}   
         9: CHANGE HOST            {1814}   
        10: unknown:2250           {2250}   
        11: ADJUSTABLE DPI         {2201}   
        12: SMART SHIFT            {2110}   
        13: HIRES WHEEL            {2121}   
            Multiplier: 15
            Has invert
              Normal wheel motion
            Has ratchet switch
              Free wheel mode
            High resolution mode
            HID notification
        14: THUMB WHEEL            {2150}   
        15: unknown:2251           {2251}   
        16: DFUCONTROL SIGNED      {00C2}   
        17: DEVICE RESET           {1802}   internal, hidden
        18: unknown:1803           {1803}   internal, hidden
        19: CONFIG DEVICE PROPS    {1806}   internal, hidden
        20: unknown:1813           {1813}   internal, hidden
        21: OOBSTATE               {1805}   internal, hidden
        22: unknown:1830           {1830}   internal, hidden
        23: unknown:1890           {1890}   internal, hidden
        24: unknown:1891           {1891}   internal, hidden
        25: unknown:18A1           {18A1}   internal, hidden
        26: unknown:1DF3           {1DF3}   internal, hidden
        27: unknown:1E00           {1E00}   hidden
        28: unknown:1EB0           {1EB0}   internal, hidden
        29: unknown:1861           {1861}   internal, hidden
        30: unknown:9001           {9001}   internal, hidden
        31: unknown:9203           {9203}   internal, hidden
        32: unknown:9205           {9205}   internal, hidden
        33: unknown:9300           {9300}   internal, hidden
     Has 8 reprogrammable keys:
         0: LEFT CLICK                , default: LeftClick                   => LEFT CLICK
             mse, pos:0, group:1, gmask:1
         1: RIGHT CLICK               , default: RightClick                  => RIGHT CLICK
             mse, pos:0, group:1, gmask:1
         2: MIDDLE BUTTON             , default: MiddleMouseButton           => MIDDLE BUTTON
             mse, reprogrammable, divertable, pos:0, group:3, gmask:7
         3: BACK AS BUTTON 4          , default: BackEx                      => BACK AS BUTTON 4
             mse, reprogrammable, divertable, pos:0, group:2, gmask:3
         4: FORWARD AS BUTTON 5       , default: BrowserForwardEx            => FORWARD AS BUTTON 5
             mse, reprogrammable, divertable, pos:0, group:2, gmask:3
         5: unknown:00C3              , default: unknown:00A9                => unknown:00C3
             mse, reprogrammable, divertable, pos:0, group:3, gmask:7
         6: unknown:00C4              , default: unknown:009D                => unknown:00C4
             mse, reprogrammable, divertable, pos:0, group:3, gmask:7
         7: unknown:00D7              , default: unknown:00B4                => unknown:00D7
             divertable, virtual, pos:0, group:4, gmask:0
     Battery: 100%, discharging.
```

**Describe the bug**
The mouse is losing its configuration (or perhaps more correctly - not being reconfigured) when waking from sleep

**To Reproduce**

Scenario 1:
1. Wake computer from sleep
2. Wiggle mouse 
- Solaar says mouse powered on
- Mouse remains in default state
3. Try to change DPI in solaar
- The DPI field greys out and cannot be further adjusted
- Mouse remains in default state
4. Remove and re-insert dongle
- Solaar reconfigures mouse and all is good

Scenario 2:
1. Wake computer from sleep
2. Wiggle mouse 
- Solaar says mouse powered on
- Mouse remains in default state
3. Exit solaar application
4. Relaunch solaar application
- Solaar reconfigures mouse and all is good 

**Additional context**
Running directly from git clione due to issues with out of date Ubuntu packages

**Comment by pfps** [comment]
Can you attach a screen shot of the Solaar window when it shows that the mouse is active but you cannot adjust the DPI?
Also, please attach the contents of ~/.config/solaar/config.json

**Comment by pfps** [comment]
I tried to reproduce your circumstances as closely as possible.  I don't have the mouse you have and the closest mouse I have uses a different receiver.  I removed the entry for this mouse from Solaar so that everything about it had to be discovered via HID++ messages.

What I did was to have solaar and the mouse active, then suspend, then turn the mouse off and on (to remove its stored state), then restore.  As soon as I restored, solaar connected to the mouse and its features could be changed.
I also tried leaving the mouse off until after I restored.  Still no problem.
So I'm stumped.

**Comment by NeonHorizon** [comment]
OK interesting, despite being able to repeat this 3 times in a row yesterday, I woke my PC from sleep this morning and scenario 1 was slightly different (perhaps it was because the machine was asleep longer so the mouse actually powered off?):

Scenario 1:
1. Wake computer from sleep
2. Wiggle mouse 
- Solaar says mouse powered on
- Mouse remains in default state
3. Change DPI in solaar
-  DPI changes but wheel resolution is still off so scrolling too slow
4. Change wheel resolution to on
- Mouse is now correct

**Comment by pfps** [comment]
Please attach a screen shot and file contents as described above.

To get more information about what Solaar is doing, run as `solaar -dd` and capture all the output in a file while trying one of your scenarios.  This will probably produce a lot of output when the mouse moves so try to reduce mouse movement as much as possible.  Attach the output that was produced.

Given that I cannot reproduce the problem locally a resolution might be difficult to achieve.

**Comment by NeonHorizon** [comment]
Sorry I forgot to include the file contents, see below...
Since its not greying out any more the screenshot wouldn't be very useful I'm guessing?
I'll try and capture some dd output for you as well.

```
{
  "4082:BA137AAB": {
    "_name": "Wireless Mouse MX Master 3",
    "dpi": "2500",
    "hires-smooth-invert": false,
    "hires-smooth-resolution": true,
    "smart-shift": 0
  },
  "_version": "1.0.1"
}
```

**Comment by NeonHorizon** [comment]
OK I think this is the relevant section between the mouse working and me hitting the sleep button and then the system and mouse being fully awake and not having any config...

Let me know if I didn't capture enough.

```
13:02:03,590    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (20) => r[10 01 4104 B28240]
13:02:03,600     INFO [ReceiverListener:hidraw0] solaar.listener: Notification(1,41,04,B28240) triggered new device <PairedDevice(1,4082,MX Master 3,BA137AAB)> (mouse)
13:02:03,600     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw0,20)>: present, 1 paired device. (0) 
13:02:03,601    DEBUG [ReceiverListener:hidraw0] logitech_receiver.notifications: <PairedDevice(1,4082,MX Master 3,BA137AAB)>: eQUAD step 4 DJ connection notification: software=True, encrypted=True, link=True, payload=True
13:02:03,601    DEBUG [MainThread] solaar.ui: status changed: <UnifyingReceiver(/dev/hidraw0,20)> (NONE) None
13:02:03,601     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <PairedDevice(1,4082,MX Master 3,BA137AAB)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 100, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY CHARGING': False, 'ERROR': None} (0)
13:02:03,601    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (20) => r[20 01 4200 0000000000000000000000]
13:02:03,601    DEBUG [ReceiverListener:hidraw0] logitech_receiver.notifications: <PairedDevice(1,4082,MX Master 3,BA137AAB)> (4.5) DJ notification Notification(1,42,00,0000000000000000000000)
13:02:03,601     INFO [ReceiverListener:hidraw0] logitech_receiver.notifications: <PairedDevice(1,4082,MX Master 3,BA137AAB)>: ignoring DJ connection: Notification(1,42,00,0000000000000000000000)
13:02:03,601    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (20) => r[11 01 0400 01010100000000000000000000000000]
13:02:03,602    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (20) <= w[10 01 011E 040000]
13:02:03,602    DEBUG [MainThread] solaar.ui: status changed: <PairedDevice(1,4082,MX Master 3,BA137AAB)> (NONE) None
13:02:03,602    DEBUG [MainThread] solaar.ui.tray: picked device with lowest battery: ('/dev/hidraw0', 1, 'Wireless Mouse MX Master 3', {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 100, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY CHARGING': False, 'ERROR': None})
13:02:03,702    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (20) => r[11 01 0700 64320000000000000000000000000000]
13:02:03,703    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (20) => r[11 01 0710 0404C078050000000000000000000000]
13:02:03,703    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (20) => r[20 01 0200 0000000000000000000000]
13:02:03,724    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (20) => r[11 01 011E 1D4B0000000000000000000000000000]
13:02:03,724    DEBUG [ReceiverListener:hidraw0] logitech_receiver.notifications: wireless status: Notification(1,04,00,01010100000000000000000000000000)
13:02:03,724     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <PairedDevice(1,4082,MX Master 3,BA137AAB)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 100, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY CHARGING': False, 'ERROR': None} (1) powered on
13:02:03,725    DEBUG [ReceiverListener:hidraw0] logitech_receiver.status: <PairedDevice(1,4082,MX Master 3,BA137AAB)>: battery 100, discharging
13:02:03,725    DEBUG [ReceiverListener:hidraw0] logitech_receiver.status: <PairedDevice(1,4082,MX Master 3,BA137AAB)>: battery 100, discharging
13:02:03,726  WARNING [ReceiverListener:hidraw0] logitech_receiver.notifications: <PairedDevice(1,4082,MX Master 3,BA137AAB)>: unknown BATTERY Notification(1,07,10,0404C078050000000000000000000000)
13:02:03,726    DEBUG [MainThread] solaar.ui: status changed: <PairedDevice(1,4082,MX Master 3,BA137AAB)> (NOTIFICATION) powered on
13:02:03,726    DEBUG [MainThread] solaar.ui.tray: picked device with lowest battery: ('/dev/hidraw0', 1, 'Wireless Mouse MX Master 3', {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 100, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY CHARGING': False, 'ERROR': None})
```

**Comment by pfps** [comment]
I don't see any problems in the log.  But I'm getting different behaviour with both my mice - on resuming from suspend I the mice are available and I can change their settings.   

What happens when you try to change the settings in your old scenario 1?  If the mouse is off but Solaar thinks it on the setting change will fail and Solaar should put a warning icon next to the setting in the window.

It may be that there is a work-around that is less drastic than the ones you have tried.  Try clicking on the receiver line in the Solaar window and then on the mouse line and see if that gets things back to normal.

**Comment by pokkos** [comment]
I've got the same behavior here with the MX Master 3 with Ubuntu 18.04 as described in scenario 2. I'm also using the current git version, the json file looks the same (beside the id) and so does the debug log as posted from @NeonHorizon.

After waking up, the settings in the ui show still the same values I set them to (2400dpi) but according to the mouse movement it is back to 1000dpi. If I change the values, I can see the change in behavior.

Stopping and restarting solaar sets the 2400dpi again until the next sleep.

Strangely, the reset to 1000dpi doesn't appear every time I wake up. The probability is about 50% (5 out of the last 10 times).

**Comment by pfps** [comment]
Here is what I think *should* be happening.  
When you suspend, nothing happens.  
If you resume soon, nothing will have changed.  The mouse should still have the same DPI (both according to Solaar and in the mouse itself).  So the speed should not have changed.  Solaar will (soon) see a connection message and try to push its DPI to the mouse but that won't change the DPI settting.
If you resume after the mouse turns itself off then Solaar will have the changed DPI setting but the mouse will (likely) have its default.  So the mouse is slower (or faster, whatever).  Solaar will (soon) see a connection message and try to push its DPI to the mouse so the mouse will change to the DPI setting you want.
But it looks like this is not happening, and I can't understand why.

There was a change to this part of Solaar in mid January, but the previous behaviour should have been worse.   To check what used to happen just before the change, you can `git checkout 77e21a0b630d2b086af47827b9fd6197ebd0a389` and then run solaar.   Please let me know your experiences.

Also let me know if the clicking-in-the-main-window workaround above is effective.

**Comment by NeonHorizon** [comment]
OK just woke up the computer this morning and the mouse had lost it config as per previous days. I opened up solaar and clicked all around it no effect. The only things which had any effect were changing the DPI which then reprogrammed the DPI on the mouse, then I changed the wheel resolution switch to get the wheel how I like it again.

**Comment by pokkos** [comment]
> There was a change to this part of Solaar in mid January, but the previous behaviour should have been worse. To check what used to happen just before the change, you can `git checkout 77e21a0b630d2b086af47827b9fd6197ebd0a389` and then run solaar. Please let me know your experiences.

I tried with this version and the behavior is exactly the same. The ui shows the values from the json file but the mouse has its default values. If I change anything in the main window, this changed value will also change on the mouse.

To dig into the code, do you have a hint where to start looking at and what might be the problem?

**Comment by pfps** [comment]
I'm not sure what the cause is here.  I suspect that the problem is that there is no description of the device in descriptors.py, but I thought I checked that by removing the description of one of my mice.
It looks as if something is going wrong in the changed function in status.py.  In that function there is an iteration over d.settings and it may be that there are no settings being set up for the mouse.  To check, uncomment the debug line just above and see what output that produces in the log.  (If it produces no output then the problem is elsewhere.)

**Comment by pfps** [comment]
I'm doing a bit of testing and ran into a bug in status.py.  If you see a complaint about  None not being iterable from line 226 of status.py change it to:
		if battery is None and d.features and _hidpp20.FEATURE.SOLAR_DASHBOARD in d.features:

**Comment by pokkos** [comment]
> Edit: Yes, this looks like the cause. Solaar doesn't notice that the mouse has been "off" and so it doesn't bother to push settings. So one workaround should be to turn the mouse off and then on again. Please report whether this works. Now to figure out how to fix the problem.

Yes, turning the mouse off and on again pushes the saved settings again to the mouse.

**Comment by pfps** [comment]
@pokkos  Your change will fix the problem, but at the cost of pushing settings to the device more often.  That may affect the behaviour of the device.
The underlying problem is, I think, that Solaar can't see that the device was disconnected because the system was suspended.  Solaar is supposed to notice resumes, but the DBUS signal that it looks for is no longer supported.  I have a change to that code that appears to fix the problem, by connecting to the current signal for that purpose.  I'll put in a PR shortly.

**Comment by pfps** [comment]
Can someone try with the current version of Solaar?  PR #693 should fix the problem.

**Comment by NeonHorizon** [comment]
I just tried unfortunately still not working here :(
Not sure if this will help...

```
20:03:59,844     INFO [MainThread] solaar.upower: received resume event
20:03:59,844    DEBUG [MainThread] logitech_receiver.base: (21) <= w[10 FF 8102 000000]
20:03:59,846    DEBUG [MainThread] logitech_receiver.base: (21) => r[10 FF 8102 000100]
20:03:59,846    DEBUG [MainThread] logitech_receiver.base: (21) pinging device 1
20:03:59,846    DEBUG [MainThread] logitech_receiver.base: (21) <= w[10 01 001A 0000A8]
20:03:59,846    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (20) => r[10 FF 8102 000100]
20:03:59,848    DEBUG [MainThread] logitech_receiver.base: (21) => r[10 01 8F00 1A0900]
20:03:59,848     INFO [MainThread] solaar.listener: status_changed <PairedDevice(1,4082,MX Master 3,BA137AAB)>: paired offline, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 100, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY CHARGING': False, 'ERROR': None} (0) 
20:03:59,848    DEBUG [MainThread] solaar.ui: status changed: <PairedDevice(1,4082,MX Master 3,BA137AAB)> (NONE) None
20:03:59,848    DEBUG [MainThread] solaar.ui.tray: picked device with lowest battery: ('/dev/hidraw0', 1, 'Wireless Mouse MX Master 3', {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 100, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY CHARGING': False, 'ERROR': None})
20:03:59,850    DEBUG [MainThread] logitech_receiver.base: (21) <= w[10 01 000E 212000]
20:03:59,850    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (20) => r[10 01 8F00 1A0900]
20:03:59,852    DEBUG [MainThread] logitech_receiver.base: (21) => r[10 01 8F00 0E0900]
20:03:59,852    DEBUG [MainThread] logitech_receiver.base: (21) device 0x01 error on request {000E}: 9 = resource error
20:03:59,852    DEBUG [MainThread] logitech_receiver.base: (21) <= w[10 01 000E 213000]
20:03:59,852    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (20) => r[10 01 8F00 0E0900]
20:03:59,854    DEBUG [MainThread] logitech_receiver.base: (21) => r[10 01 8F00 0E0900]
20:03:59,854    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (20) => r[10 01 8F00 0E0900]
20:03:59,854    DEBUG [MainThread] logitech_receiver.base: (21) device 0x01 error on request {000E}: 9 = resource error
20:03:59,854    DEBUG [MainThread] logitech_receiver.base: (21) <= w[10 01 0008 40A000]
20:03:59,856    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (20) => r[10 01 8F00 080900]
20:03:59,856    DEBUG [MainThread] logitech_receiver.base: (21) => r[10 01 8F00 080900]
20:03:59,856    DEBUG [MainThread] logitech_receiver.base: (21) device 0x01 error on request {0008}: 9 = resource error
20:03:59,856    DEBUG [MainThread] logitech_receiver.base: (21) <= w[10 01 000A 40A200]
20:03:59,858    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (20) => r[10 01 8F00 0A0900]
20:03:59,858    DEBUG [MainThread] logitech_receiver.base: (21) => r[10 01 8F00 0A0900]
20:03:59,858    DEBUG [MainThread] logitech_receiver.base: (21) device 0x01 error on request {000A}: 9 = resource error
20:03:59,858    DEBUG [MainThread] logitech_receiver.base: (21) <= w[10 01 0009 40A300]
20:03:59,860    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (20) => r[10 01 8F00 090900]
20:03:59,860    DEBUG [MainThread] logitech_receiver.base: (21) => r[10 01 8F00 090900]
20:03:59,860    DEBUG [MainThread] logitech_receiver.base: (21) device 0x01 error on request {0009}: 9 = resource error
20:03:59,860    DEBUG [MainThread] logitech_receiver.base: (21) <= w[10 01 000D 220500]
20:03:59,862    DEBUG [MainThread] logitech_receiver.base: (21) => r[10 01 8F00 0D0900]
20:03:59,862    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (20) => r[10 01 8F00 0D0900]
20:03:59,862    DEBUG [MainThread] logitech_receiver.base: (21) device 0x01 error on request {000D}: 9 = resource error
20:03:59,862    DEBUG [MainThread] logitech_receiver.base: (21) <= w[10 01 0009 198200]
20:03:59,864    DEBUG [MainThread] logitech_receiver.base: (21) => r[10 01 8F00 090900]
20:03:59,864    DEBUG [MainThread] logitech_receiver.base: (21) device 0x01 error on request {0009}: 9 = resource error
20:03:59,864    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (20) => r[10 01 8F00 090900]
20:03:59,864    DEBUG [AsyncUI] logitech_receiver.settings: hires-smooth-invert: settings read False from <PairedDevice(1,4082,MX Master 3,BA137AAB)>
20:03:59,864    DEBUG [AsyncUI] logitech_receiver.settings: hires-smooth-resolution: settings read True from <PairedDevice(1,4082,MX Master 3,BA137AAB)>
20:03:59,864    DEBUG [AsyncUI] logitech_receiver.settings: dpi: settings read '2500' from <PairedDevice(1,4082,MX Master 3,BA137AAB)>
20:03:59,864    DEBUG [AsyncUI] logitech_receiver.settings: smart-shift: settings read 0 from <PairedDevice(1,4082,MX Master 3,BA137AAB)>
```

**Comment by pfps** [comment]
Rats.
Did all the messages above come before you wiggled the mouse?

**Comment by NeonHorizon** [comment]
Yes

**Comment by pokkos** [comment]
I also get a lot of the same `device 0x01 error on request {0009}: 9 = resource error`. And the settings are not pushed back after suspend.

And btw: even with the hard-coded `True` I mentioned above, after the suspend over night it didn't push the settings back.

**Comment by pokkos** [comment]
> Can someone try with the current version of Solaar? PR #693 should fix the problem.

I got rid of the error messages at least. It seems there is a bug in this commit. In line 78 `dbus_interface` and `bus_name` are in the wrong order when not using keywords.

But still, the settings don't get pushed back after waking up.

**Comment by pfps** [comment]
I've found the source of the `resource error` messages, but it seems somewhat benign.

**Comment by pfps** [comment]
@pokkos Oops.  But their values were also switched so two wrongs made a right.  But two wrongs are also still two wrongs, so I fixed up the code.

**Comment by pfps** [comment]
PR #695 *should* fix the problem.  At least it fixes my recreation of the problem with different hardware.

**Comment by pokkos** [comment]
It seems to have fixed my problem too so far. My mouse had its settings back after waking up over night. Thanks for the fix @pfps ;)

**Comment by pfps** [comment]
OK, closing.

**Comment by anathonous** [comment]
I am having a similar issue with a MX Mouse S2. Upon waking from sleep I lose all settings, my gestures disappear and my scroll wheel locks. You should write a systemd service that loads and the solaar gui has access too, when detecting a wake from sleep the solaar service reloads.

**Comment by pfps** [comment]
Solaar already tries to recover from sleep.   On my system Solaar reapplies all settings when it first sees devices after resuming from sleep and when devices ask for reconfiguration.  

To see what is happening for you, you need to run Solaar as `solaar -ddd` and post the output around the time of waking when you lose settings.

**Comment by pfps** [comment]
I forgot that there is a recent change to Solaar to undo a change that caused Solaar to sometimes not reapply settings after sleep.  So you should probably first clone the Solaar repository and run Solaar from there.

**Comment by anathonous** [comment]
I'll let the package manager for gentoo know. It's much easier than
monitoring GitHub changes. Not a major issue. Maybe I'll put some work into
a Solaar wiki article on the Gentoo wiki site. I made one for bolt
receivers.

**Comment by robbat2** [comment]
@pfps tag a new release so @anathonous gets their fix?

**Comment by pfps** [comment]
An rc will go out soon.

**Comment by upward4** [comment]
I know this appears to be fixed, but I still have this issue on 1.1.5. The mouse does not remember the ratchet setting that was set with the dedicated hardware button before sleep.

**Comment by pfps** [comment]
Please provide the sequence of actions that cause the problems.  Also run `solaar show` after you set the ratchet setting and then again after the mouse wakes from sleep.

**Comment by upward4** [comment]
Steps to reproduces:

1. Disable ratchet mode with HW button
2. Put OS into sleep
3. Resume from sleep
4. Ratchet mode is automatically engaged on the mouse (you can hear the mechanical switch)

`solaar show` after disabling ratchet mode with the HW button on the mouse:

```
Solaar version 1.1.5

Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:C52B
  Serial       : 428993A0
    Firmware   : 24.11.B0036
    Bootloader : 02.09
    Other      : AA.AC
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 2=84

  1: ERGO M575
     Device path  : /dev/hidraw1
     WPID         : 4096
     Codename     : ERGO M575
     Kind         : mouse
     Protocol     : unknown (device is offline)
     Polling rate : 8 ms (125Hz)
     Serial number: BC4AE425
     The power switch is located on the base.
     Battery: unknown (device is offline).

  2: Wireless Mouse MX Master
     Device path  : /dev/hidraw2
     WPID         : 4071
     Codename     : MX Master
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 13CDB00E
     Model ID:      B01E40710000
     Unit ID:       5D96335E
        Bootloader: BOT 56.10.B0005
          Firmware: MPM 12.10.B0005
          Firmware: MPM 12.10.B0005
             Other: 
     The power switch is located on the base.
     Supports 31 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V2     
            Firmware: Bootloader BOT 56.10.B0005 40717622661101
            Firmware: Firmware MPM 12.10.B0005 B01E7622661101
            Firmware: Firmware MPM 12.10.B0005 40717622661101
            Firmware: Other   
            Unit ID: 5D96335E  Model ID: B01E40710000  Transport IDs: {'btleid': 'B01E', 'wpid': '4071'}
         3: DEVICE NAME            {0005} V0     
            Name: Wireless Mouse MX Master
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: RESET                  {0020} V0     
         6: CRYPTO ID              {0021} V0     
         7: BATTERY STATUS         {1000} V0     
            Battery: 20%, discharging, next level 5%.
         8: CONFIG DEVICE PROPS    {1806} V0    internal, hidden 
         9: CHANGE HOST            {1814} V1     
            Change Host        : 1:earth
        10: REPROG CONTROLS V4     {1B04} V3     
            Key/Button Actions (saved): {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Key/Button Actions        : {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Key/Button Diversion (saved): {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Regular, Smart Shift:Regular}
            Key/Button Diversion        : {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Regular, Smart Shift:Regular}
        11: ADJUSTABLE DPI         {2201} V1     
            Sensitivity (DPI) (saved): 1400
            Sensitivity (DPI)        : 1400
        12: VERTICAL SCROLLING     {2100} V0     
            Roller type: 3G
            Ratchet per turn: 24
            Scroll lines: 0
        13: SMART SHIFT            {2110} V0     
            Scroll Wheel Rachet (saved): 20
            Scroll Wheel Rachet        : 0
        14: HIRES WHEEL            {2121} V0     
            Multiplier: 8
            Has invert: Normal wheel motion
            Has ratchet switch: Free wheel mode
            High resolution mode
            HID notification
            Scroll Wheel Direction (saved): False
            Scroll Wheel Direction        : False
            Scroll Wheel Resolution (saved): True
            Scroll Wheel Resolution        : True
            Scroll Wheel Diversion (saved): False
            Scroll Wheel Diversion        : False
        15: GESTURE 2              {6501} V0     
            Gestures (saved): {45: True, 46: True}
            Gestures        : {46: True, 45: True}
            Gestures Diversion (saved): {46: False}
            Gestures Diversion        : {46: False}
        16: DFUCONTROL SIGNED      {00C2} V0     
        17: unknown:1813           {1813} V0    internal, hidden 
        18: unknown:1830           {1830} V0    internal, hidden 
        19: unknown:1890           {1890} V0    internal, hidden 
        20: unknown:1891           {1891} V0    internal, hidden 
        21: unknown:18A1           {18A1} V0    internal, hidden 
        22: unknown:18C0           {18C0} V0    internal, hidden 
        23: unknown:1DF3           {1DF3} V0    internal, hidden 
        24: unknown:1E00           {1E00} V0    hidden 
        25: unknown:1EB0           {1EB0} V0    internal, hidden 
        26: unknown:1803           {1803} V0    internal, hidden 
        27: unknown:1861           {1861} V0    internal, hidden 
        28: unknown:9001           {9001} V0    internal, hidden 
        29: unknown:9200           {9200} V0    internal, hidden 
        30: unknown:9202           {9202} V0    internal, hidden 
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: Mouse Gesture Button      , default: Gesture Button Navigation   => Gesture Button Navigation 
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         6: Smart Shift               , default: Smart Shift                 => Smart Shift               
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
             reporting: default
     Has 2 gesture(s), 0 param(s) and 4 spec(s):
        Thumbwheel                 Enabled(   0): True   Diverted:(   0) False
        NaturalScrolling           Enabled(   1): True   Diverted:(None) None
        period unit                Spec   (   3): 800
        DVI field width            Spec   (   1): 8
        field widths               Spec   (   2): 8
        resolution                 Spec   (   4): 2048
     Battery: 20%, discharging, next level 5%.
```

`solaar show` after resume from sleep:

```
Solaar version 1.1.5

Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:C52B
  Serial       : 428993A0
    Firmware   : 24.11.B0036
    Bootloader : 02.09
    Other      : AA.AC
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 2=116

  1: ERGO M575
     Device path  : /dev/hidraw1
     WPID         : 4096
     Codename     : ERGO M575
     Kind         : mouse
     Protocol     : unknown (device is offline)
     Polling rate : 8 ms (125Hz)
     Serial number: BC4AE425
     The power switch is located on the base.
     Battery: unknown (device is offline).

  2: Wireless Mouse MX Master
     Device path  : /dev/hidraw2
     WPID         : 4071
     Codename     : MX Master
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 13CDB00E
     Model ID:      B01E40710000
     Unit ID:       5D96335E
        Bootloader: BOT 56.10.B0005
          Firmware: MPM 12.10.B0005
          Firmware: MPM 12.10.B0005
             Other: 
     The power switch is located on the base.
     Supports 31 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V2     
            Firmware: Bootloader BOT 56.10.B0005 40717622661101
            Firmware: Firmware MPM 12.10.B0005 B01E7622661101
            Firmware: Firmware MPM 12.10.B0005 40717622661101
            Firmware: Other   
            Unit ID: 5D96335E  Model ID: B01E40710000  Transport IDs: {'btleid': 'B01E', 'wpid': '4071'}
         3: DEVICE NAME            {0005} V0     
            Name: Wireless Mouse MX Master
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: RESET                  {0020} V0     
         6: CRYPTO ID              {0021} V0     
         7: BATTERY STATUS         {1000} V0     
            Battery: 20%, discharging, next level 5%.
         8: CONFIG DEVICE PROPS    {1806} V0    internal, hidden 
         9: CHANGE HOST            {1814} V1     
            Change Host        : 1:earth
        10: REPROG CONTROLS V4     {1B04} V3     
            Key/Button Actions (saved): {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Key/Button Actions        : {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Key/Button Diversion (saved): {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Regular, Smart Shift:Regular}
            Key/Button Diversion        : {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Regular, Smart Shift:Regular}
        11: ADJUSTABLE DPI         {2201} V1     
            Sensitivity (DPI) (saved): 1400
            Sensitivity (DPI)        : 1400
        12: VERTICAL SCROLLING     {2100} V0     
            Roller type: 3G
            Ratchet per turn: 24
            Scroll lines: 0
        13: SMART SHIFT            {2110} V0     
            Scroll Wheel Rachet (saved): 20
            Scroll Wheel Rachet        : 20
        14: HIRES WHEEL            {2121} V0     
            Multiplier: 8
            Has invert: Normal wheel motion
            Has ratchet switch: Normal wheel mode
            High resolution mode
            HID notification
            Scroll Wheel Direction (saved): False
            Scroll Wheel Direction        : False
            Scroll Wheel Resolution (saved): True
            Scroll Wheel Resolution        : True
            Scroll Wheel Diversion (saved): False
            Scroll Wheel Diversion        : False
        15: GESTURE 2              {6501} V0     
            Gestures (saved): {45: True, 46: True}
            Gestures        : {46: True, 45: True}
            Gestures Diversion (saved): {46: False}
            Gestures Diversion        : {46: False}
        16: DFUCONTROL SIGNED      {00C2} V0     
        17: unknown:1813           {1813} V0    internal, hidden 
        18: unknown:1830           {1830} V0    internal, hidden 
        19: unknown:1890           {1890} V0    internal, hidden 
        20: unknown:1891           {1891} V0    internal, hidden 
        21: unknown:18A1           {18A1} V0    internal, hidden 
        22: unknown:18C0           {18C0} V0    internal, hidden 
        23: unknown:1DF3           {1DF3} V0    internal, hidden 
        24: unknown:1E00           {1E00} V0    hidden 
        25: unknown:1EB0           {1EB0} V0    internal, hidden 
        26: unknown:1803           {1803} V0    internal, hidden 
        27: unknown:1861           {1861} V0    internal, hidden 
        28: unknown:9001           {9001} V0    internal, hidden 
        29: unknown:9200           {9200} V0    internal, hidden 
        30: unknown:9202           {9202} V0    internal, hidden 
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: Mouse Gesture Button      , default: Gesture Button Navigation   => Gesture Button Navigation 
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         6: Smart Shift               , default: Smart Shift                 => Smart Shift               
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
             reporting: default
     Has 2 gesture(s), 0 param(s) and 4 spec(s):
        Thumbwheel                 Enabled(   0): True   Diverted:(   0) False
        NaturalScrolling           Enabled(   1): True   Diverted:(None) None
        period unit                Spec   (   3): 800
        DVI field width            Spec   (   1): 8
        field widths               Spec   (   2): 8
        resolution                 Spec   (   4): 2048
     Battery: 20%, discharging, next level 5%.
```

**Comment by pfps** [comment]
I think that the problem here is that Solaar does not keep track of changes made to the ratchet switch by using the smart shift button.   This is different from the problem in this issue.

Please open a new issue about this problem.

**Comment by visualcortexlab** [comment]
hi there, I just got my MX anywhere 3S (had a 2S for years) and since the middle button wasn't set the same as the 2S (tiny button instead of wheel) I bumped into Solaar. cool app! altho I'm suffering from the same issue, got up this morning and, after resuming from the screen saver (only screen blanked, system was still up) the middle button was gone and I can't find a way to get the mouse recognized/setup again. 
Haven't rebooted yet.

some infos here:

uname -ar
Linux JcN-XeonRTX 6.9.10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.9.10-1 (2024-07-19) x86_64 GNU/Linux

my config.yaml 

- 1.1.8+dfsg-2
- _NAME: MX Anywhere 3S
  _absent: [hi-res-scroll, lowres-scroll-mode, scroll-ratchet, report_rate, pointer_speed, dpi, speed-change, back
light, backlight-timed, fn-swap, persistent-remappable-keys,
    disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gestur
e2-gestures, gesture2-divert, gesture2-params,
    sidetone, equalizer]
  _battery: 4097
  _modelId: B03700000000
  _sensitive: {divert-keys: true, onboard_profiles: true}
  _unitId: 58D6D621
  change-host: null
  divert-keys: {82: 1, 83: 0, 86: 0}
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  onboard_profiles: 1
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 196: 196}
  smart-shift: 10
  thumb-scroll-invert: false
  thumb-scroll-mode: false

**Comment by visualcortexlab** [comment]
Update: after turning off->on the mouse itself nothing was fixed, in fact things got little worst inside the Solaar UI.

however, after switching the mouse channel from 1 to 2 and then back to 1 I got the wheel MMB again.
Relaunching Solaar brought back all the options and I could re-setup my "smart-shift button" to "mouse middle mouse" (which is my preferred setup instead of the wheel).

my  config.yaml after the channel switch and Solaar re-setup: 
- 1.1.8+dfsg-2
- _NAME: MX Anywhere 3S
  _absent: [hi-res-scroll, lowres-scroll-mode, scroll-ratchet, report_rate, pointer_speed, dpi, speed-change, back
light, backlight-timed, fn-swap, persistent-remappable-keys,
    disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gestur
e2-gestures, gesture2-divert, gesture2-params,
    sidetone, equalizer]
  _battery: 4097
  _modelId: B03700000000
  _sensitive: {divert-keys: true, onboard_profiles: true, reprogrammable-keys: true}
  _unitId: 58D6D621
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0}
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  onboard_profiles: 1
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 196: 82}
  smart-shift: 10
  thumb-scroll-invert: false
  thumb-scroll-mode: false

**Comment by pfps** [comment]
Please open a new bug issue for this.  Also, are you connecting via Bluetooth?

**Comment by visualcortexlab** [comment]
Yeah, Thinkpad's bluetooth's straight.
Cool, I'll open a new one and report the above. thanks! :)

**Comment by visualcortexlab** [comment]
Opened a new BUG [here](https://github.com/pwr-Solaar/Solaar/issues/2636)
